apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: backend-config
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: true
